-- MySQL Script generated by MySQL Workbench
-- Sun Nov 12 22:38:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marcosvir_santoro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marcosvir_santoro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS marcosvir_santoro DEFAULT CHARACTER SET utf8 ;
USE marcosvir_santoro ;

-- -----------------------------------------------------
-- Table marcosvir_santoro.Carrinho
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS marcosvir_santoro.Carrinho (
  idCarrinho INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (idCarrinho),
  UNIQUE INDEX idCarrinho_UNIQUE (idCarrinho ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table marcosvir_santoro.Cor
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS marcosvir_santoro.Cor (
  idCor INT NOT NULL,
  cor VARCHAR(45) NOT NULL,
  PRIMARY KEY (idCor))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table marcosvir_santoro.Produto
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS marcosvir_santoro.Produto (
  idProduto INT NOT NULL,
  produto VARCHAR(45) NOT NULL,
  PRIMARY KEY (idProduto),
  UNIQUE INDEX idProduto_UNIQUE (idProduto ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table marcosvir_santoro.Tamanho
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS marcosvir_santoro.Tamanho (
  idTamanho INT NOT NULL,
  tamanho VARCHAR(45) NOT NULL,
  PRIMARY KEY (idTamanho))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table marcosvir_santoro.Pedido
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS marcosvir_santoro.Pedido (
  idPedido INT NOT NULL AUTO_INCREMENT,
  qtd INT NOT NULL,
  Carrinho_idCarrinho INT NOT NULL,
  Cor_idCor INT NOT NULL,
  Produto_idProduto INT NOT NULL,
  Tamanho_idTamanho INT NOT NULL,
  PRIMARY KEY (idPedido),
  INDEX fk_Pedido_Carrinho1_idx (Carrinho_idCarrinho ASC) VISIBLE,
  UNIQUE INDEX idPedido_UNIQUE (idPedido ASC) VISIBLE,
  INDEX fk_Pedido_Cor1_idx (Cor_idCor ASC) VISIBLE,
  INDEX fk_Pedido_Produto1_idx (Produto_idProduto ASC) VISIBLE,
  INDEX fk_Pedido_Tamanho1_idx (Tamanho_idTamanho ASC) VISIBLE,
  CONSTRAINT fk_Pedido_Carrinho1
    FOREIGN KEY (Carrinho_idCarrinho)
    REFERENCES marcosvir_santoro.Carrinho (idCarrinho)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Pedido_Cor1
    FOREIGN KEY (Cor_idCor)
    REFERENCES marcosvir_santoro.Cor (idCor)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Pedido_Produto1
    FOREIGN KEY (Produto_idProduto)
    REFERENCES marcosvir_santoro.Produto (idProduto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Pedido_Tamanho1
    FOREIGN KEY (Tamanho_idTamanho)
    REFERENCES marcosvir_santoro.Tamanho (idTamanho)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;corpedidoprodutotamanhocarrinho

INSERT INTO marcosvir_santoro.Tamanho (idTamanho, tamanho) VALUES (1, 'P');
INSERT INTO marcosvir_santoro.Tamanho (idTamanho, tamanho) VALUES (2, 'M');
INSERT INTO marcosvir_santoro.Tamanho (idTamanho, tamanho) VALUES (3, 'G');
INSERT INTO marcosvir_santoro.Tamanho (idTamanho, tamanho) VALUES (4, 'GG');

INSERT INTO marcosvir_santoro.Produto (idProduto, produto) VALUES (1, 'Camiseta');
INSERT INTO marcosvir_santoro.Produto (idProduto, produto) VALUES (2, 'Camisa');
INSERT INTO marcosvir_santoro.Produto (idProduto, produto) VALUES (3, 'Casaco');
INSERT INTO marcosvir_santoro.Produto (idProduto, produto) VALUES (4, 'Moleton');

INSERT INTO marcosvir_santoro.Cor (idCor, cor) VALUES (1, 'Branco');
INSERT INTO marcosvir_santoro.Cor (idCor, cor) VALUES (2, 'Preto');
INSERT INTO marcosvir_santoro.Cor (idCor, cor) VALUES (3, 'Cinza');
INSERT INTO marcosvir_santoro.Cor (idCor, cor) VALUES (4, 'Azul');
INSERT INTO marcosvir_santoro.Cor (idCor, cor) VALUES (5, 'Amarelo');
INSERT INTO marcosvir_santoro.Cor (idCor, cor) VALUES (6, 'Vermelho');